import { NextRequest, NextResponse } from 'next/server'
import { getPayload } from 'payload'
import config from '@payload-config'

/**
 * Pre-create a minimal draft episode
 * POST /api/episodes/new-draft
 * 
 * Auth: host/staff/admin only
 * Body: { showId?: string } (optional)
 * 
 * Creates a minimal Episode with:
 * - publishedStatus: 'draft'
 * - pendingReview: false
 * - show: showId (if provided)
 * - hosts: [currentHostId]
 * - createdBy: currentUserId (for auditable ownership)
 * 
 * Returns: { id: string }
 */
export async function POST(req: NextRequest) {
  try {
    const payload = await getPayload({ config })

    // Get authenticated user from Payload
    const { user } = await payload.auth({ headers: req.headers })

    // Access Control: host/staff/admin only
    if (!user || !['admin', 'staff', 'host'].includes((user as any).role)) {
      return NextResponse.json(
        { error: 'Forbidden: Host, Staff, or Admin access required' },
        { status: 403 },
      )
    }

    // Parse request body
    const body = await req.json().catch(() => ({}))
    const { showId } = body

    // Get host ID for the current user
    let hostId: string | null = null
    if ((user as any).role === 'host' && (user as any).host) {
      hostId = typeof (user as any).host === 'string' 
        ? (user as any).host 
        : (user as any).host.id
    }

    // Build minimal episode data
    const episodeData: any = {
      publishedStatus: 'draft',
      pendingReview: false,
      createdBy: user.id,
      publishedAt: new Date().toISOString(), // Default to current date
    }

    // Add show if provided
    if (showId) {
      episodeData.show = showId
    }

    // Add host if available (hosts can only create episodes for themselves)
    if (hostId) {
      episodeData.hosts = [hostId]
    }

    // Create the episode (slug will be auto-generated by beforeChange hook)
    const episode = await payload.create({
      collection: 'episodes',
      data: episodeData,
    })
    
    console.log(`[new-draft] Episode created with slug: ${episode.slug}`)

    console.log(`[new-draft] Created draft episode ${episode.id} for user ${user.email}`)

    return NextResponse.json({
      id: episode.id,
      success: true,
    })
  } catch (error: any) {
    console.error('[new-draft] Error creating draft episode:', error)
    return NextResponse.json(
      { 
        error: error.message || 'Failed to create draft episode',
        success: false,
      },
      { status: 500 },
    )
  }
}

