/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'media-images': MediaImage;
    'media-tracks': MediaTrack;
    episodes: Episode;
    shows: Show;
    hosts: Host;
    genres: Genre;
    'upload-error-logs': UploadErrorLog;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    shows: {
      episodes: 'episodes';
    };
    hosts: {
      shows: 'shows';
      episodes: 'episodes';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'media-images': MediaImagesSelect<false> | MediaImagesSelect<true>;
    'media-tracks': MediaTracksSelect<false> | MediaTracksSelect<true>;
    episodes: EpisodesSelect<false> | EpisodesSelect<true>;
    shows: ShowsSelect<false> | ShowsSelect<true>;
    hosts: HostsSelect<false> | HostsSelect<true>;
    genres: GenresSelect<false> | GenresSelect<true>;
    'upload-error-logs': UploadErrorLogsSelect<false> | UploadErrorLogsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  role: 'admin' | 'staff' | 'host' | 'user';
  /**
   * Host profile associated with this user (for episode uploads)
   */
  host?: (string | null) | Host;
  favorites?: (string | Episode)[] | null;
  favoriteShows?: (string | Show)[] | null;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hosts".
 */
export interface Host {
  id: string;
  name: string;
  bio?: string | null;
  photo?: (string | null) | Media;
  socials?:
    | {
        url: string;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  type?: ('resident' | 'guest') | null;
  /**
   * User account associated with this host (for upload permissions)
   */
  user?: (string | null) | User;
  shows?: {
    docs?: (string | Show)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  episodes?: {
    docs?: (string | Episode)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  status?: ('active' | 'inactive') | null;
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shows".
 */
export interface Show {
  id: string;
  title: string;
  subtitle?: string | null;
  description?: string | null;
  cover?: (string | null) | MediaImage;
  hosts?: (string | Host)[] | null;
  genres?: (string | Genre)[] | null;
  episodes?: {
    docs?: (string | Episode)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  slug?: string | null;
  status: 'active' | 'archived';
  visibility?: ('public' | 'unlisted') | null;
  homepageFeatured?: boolean | null;
  airState: 'live' | 'preRecorded';
  launchedAt?: string | null;
  show_type?:
    | (
        | 'Résidents'
        | 'Guests'
        | 'Live'
        | 'Hors Murs'
        | 'Podcasts'
        | 'One off'
        | 'Compositions Sonores'
        | 'Retransmissions'
        | 'Takeover'
      )[]
    | null;
  /**
   * ID of the show in LibreTime system
   */
  libretimeShowId?: number | null;
  libretimeInstanceId: 'main';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-images".
 */
export interface MediaImage {
  id: string;
  /**
   * Alt text for accessibility
   */
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "genres".
 */
export interface Genre {
  id: string;
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "episodes".
 */
export interface Episode {
  id: string;
  title?: string | null;
  show?: (string | null) | Show;
  hosts?: (string | Host)[] | null;
  description?: string | null;
  /**
   * Paste your tracklist here (one track per line)
   */
  tracklistRaw?: string | null;
  cover?: (string | null) | MediaImage;
  publishedAt: string;
  duration?: number | null;
  roundedDuration?: number | null;
  energy?: ('low' | 'medium' | 'high') | null;
  mood?:
    | ('' | 'sedative' | 'cozy' | 'groovy' | 'club' | 'adrenaline' | 'hard' | 'psychedelic' | 'leftfield' | 'research')
    | null;
  tone?: ('dark' | 'bright' | 'melancholic' | 'dreamy' | 'nostalgic' | 'neutral') | null;
  genres?: (string | Genre)[] | null;
  publishedStatus: 'draft' | 'submitted' | 'published' | 'scheduled';
  /**
   * Episode uploaded by host, awaiting admin/staff approval
   */
  pendingReview?: boolean | null;
  visibility?: ('public' | 'unlisted') | null;
  /**
   * Mark this episode as a DIA! selection.
   */
  diaPick?: boolean | null;
  type?:
    | (
        | 'Résidents'
        | 'Guests'
        | 'Live'
        | 'Hors Murs'
        | 'Podcasts'
        | 'One off'
        | 'Compositions Sonores'
        | 'Retransmissions'
        | 'Takeover'
      )[]
    | null;
  airState?: ('live' | 'preRecorded') | null;
  showStatus?: ('active' | 'archived') | null;
  /**
   * When this episode is scheduled to air
   */
  scheduledAt?: string | null;
  /**
   * When this episode is scheduled to end
   */
  scheduledEnd?: string | null;
  airStatus: 'draft' | 'queued' | 'scheduled' | 'airing' | 'aired' | 'failed';
  media?: (string | null) | MediaTrack;
  /**
   * ID from LibreTime system for this track
   */
  libretimeTrackId?: string | null;
  /**
   * Relative file path in LibreTime library (e.g., imported/1/filename.mp3)
   */
  libretimeFilepathRelative?: string | null;
  /**
   * Whether this episode has been archived to file system
   */
  hasArchiveFile?: boolean | null;
  /**
   * Path to archived file
   */
  archiveFilePath?: string | null;
  /**
   * ID of the show instance in LibreTime
   */
  libretimeInstanceId?: number | null;
  /**
   * ID of the scheduled playout in LibreTime
   */
  libretimePlayoutId?: number | null;
  soundcloud?: string | null;
  scPermalink?: string | null;
  scSlug?: string | null;
  track_id?: number | null;
  mp3_url?: string | null;
  bitrate?: number | null;
  realDuration?: number | null;
  waveform?: string | null;
  coverExternal?: string | null;
  plays?: number | null;
  likes?: number | null;
  airplayHours?: number | null;
  firstAiredAt?: string | null;
  lastAiredAt?: string | null;
  airCount?: number | null;
  adminNotes?: string | null;
  /**
   * User who completed classification
   */
  categorizedBy?: string | null;
  /**
   * When classification was completed
   */
  categorizedAt?: string | null;
  episodeNumber?: string | null;
  slug?: string | null;
  realDurationDisplay?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-tracks".
 */
export interface MediaTrack {
  id: string;
  /**
   * Unique track ID for LibreTime integration
   */
  trackId?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {};
}
/**
 * Logs of all upload errors for episodes and media
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "upload-error-logs".
 */
export interface UploadErrorLog {
  id: string;
  /**
   * User who encountered the error
   */
  user: string | User;
  /**
   * Email of the user (cached for convenience)
   */
  userEmail?: string | null;
  /**
   * Role of the user at time of error
   */
  userRole?: string | null;
  /**
   * Collection where the error occurred
   */
  collection: 'episodes' | 'media-tracks' | 'media-images' | 'shows';
  /**
   * Operation being attempted
   */
  operation: 'create' | 'update' | 'upload';
  /**
   * Type/category of error
   */
  errorType: 'validation' | 'audio_quality' | 'file_upload' | 'permission' | 'server' | 'other';
  /**
   * Specific error code (e.g., BITRATE_TOO_LOW, DURATION_MISMATCH)
   */
  errorCode?: string | null;
  /**
   * Full error message shown to user
   */
  errorMessage: string;
  /**
   * Stack trace for debugging
   */
  stackTrace?: string | null;
  /**
   * Additional context (file info, validation details, etc.)
   */
  context?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * HTTP status code returned
   */
  httpStatus?: number | null;
  /**
   * ID of document being created/updated (if available)
   */
  targetDocumentId?: string | null;
  /**
   * IP address of the request
   */
  ipAddress?: string | null;
  /**
   * Browser user agent
   */
  userAgent?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'media-images';
        value: string | MediaImage;
      } | null)
    | ({
        relationTo: 'media-tracks';
        value: string | MediaTrack;
      } | null)
    | ({
        relationTo: 'episodes';
        value: string | Episode;
      } | null)
    | ({
        relationTo: 'shows';
        value: string | Show;
      } | null)
    | ({
        relationTo: 'hosts';
        value: string | Host;
      } | null)
    | ({
        relationTo: 'genres';
        value: string | Genre;
      } | null)
    | ({
        relationTo: 'upload-error-logs';
        value: string | UploadErrorLog;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  host?: T;
  favorites?: T;
  favoriteShows?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  _verified?: T;
  _verificationToken?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-images_select".
 */
export interface MediaImagesSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-tracks_select".
 */
export interface MediaTracksSelect<T extends boolean = true> {
  trackId?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?: T | {};
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "episodes_select".
 */
export interface EpisodesSelect<T extends boolean = true> {
  title?: T;
  show?: T;
  hosts?: T;
  description?: T;
  tracklistRaw?: T;
  cover?: T;
  publishedAt?: T;
  duration?: T;
  roundedDuration?: T;
  energy?: T;
  mood?: T;
  tone?: T;
  genres?: T;
  publishedStatus?: T;
  pendingReview?: T;
  visibility?: T;
  diaPick?: T;
  type?: T;
  airState?: T;
  showStatus?: T;
  scheduledAt?: T;
  scheduledEnd?: T;
  airStatus?: T;
  media?: T;
  libretimeTrackId?: T;
  libretimeFilepathRelative?: T;
  hasArchiveFile?: T;
  archiveFilePath?: T;
  libretimeInstanceId?: T;
  libretimePlayoutId?: T;
  soundcloud?: T;
  scPermalink?: T;
  scSlug?: T;
  track_id?: T;
  mp3_url?: T;
  bitrate?: T;
  realDuration?: T;
  waveform?: T;
  coverExternal?: T;
  plays?: T;
  likes?: T;
  airplayHours?: T;
  firstAiredAt?: T;
  lastAiredAt?: T;
  airCount?: T;
  adminNotes?: T;
  categorizedBy?: T;
  categorizedAt?: T;
  episodeNumber?: T;
  slug?: T;
  realDurationDisplay?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shows_select".
 */
export interface ShowsSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  description?: T;
  cover?: T;
  hosts?: T;
  genres?: T;
  episodes?: T;
  slug?: T;
  status?: T;
  visibility?: T;
  homepageFeatured?: T;
  airState?: T;
  launchedAt?: T;
  show_type?: T;
  libretimeShowId?: T;
  libretimeInstanceId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hosts_select".
 */
export interface HostsSelect<T extends boolean = true> {
  name?: T;
  bio?: T;
  photo?: T;
  socials?:
    | T
    | {
        url?: T;
        label?: T;
        id?: T;
      };
  type?: T;
  user?: T;
  shows?: T;
  episodes?: T;
  status?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "genres_select".
 */
export interface GenresSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "upload-error-logs_select".
 */
export interface UploadErrorLogsSelect<T extends boolean = true> {
  user?: T;
  userEmail?: T;
  userRole?: T;
  collection?: T;
  operation?: T;
  errorType?: T;
  errorCode?: T;
  errorMessage?: T;
  stackTrace?: T;
  context?: T;
  httpStatus?: T;
  targetDocumentId?: T;
  ipAddress?: T;
  userAgent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}